# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/juntan/projects/executorch

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/juntan/projects/executorch

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/juntan/projects/executorch/CMakeFiles /home/juntan/projects/executorch//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/juntan/projects/executorch/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named executorch_core

# Build rule for target.
executorch_core: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 executorch_core
.PHONY : executorch_core

# fast build rule for target.
executorch_core/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executorch_core.dir/build.make CMakeFiles/executorch_core.dir/build
.PHONY : executorch_core/fast

#=============================================================================
# Target rules for targets named executorch

# Build rule for target.
executorch: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 executorch
.PHONY : executorch

# fast build rule for target.
executorch/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executorch.dir/build.make CMakeFiles/executorch.dir/build
.PHONY : executorch/fast

#=============================================================================
# Target rules for targets named executor_runner

# Build rule for target.
executor_runner: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 executor_runner
.PHONY : executor_runner

# fast build rule for target.
executor_runner/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executor_runner.dir/build.make CMakeFiles/executor_runner.dir/build
.PHONY : executor_runner/fast

#=============================================================================
# Target rules for targets named flatbuffers_ep

# Build rule for target.
flatbuffers_ep: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 flatbuffers_ep
.PHONY : flatbuffers_ep

# fast build rule for target.
flatbuffers_ep/fast:
	$(MAKE) $(MAKESILENT) -f third-party/CMakeFiles/flatbuffers_ep.dir/build.make third-party/CMakeFiles/flatbuffers_ep.dir/build
.PHONY : flatbuffers_ep/fast

#=============================================================================
# Target rules for targets named flatcc_ep

# Build rule for target.
flatcc_ep: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 flatcc_ep
.PHONY : flatcc_ep

# fast build rule for target.
flatcc_ep/fast:
	$(MAKE) $(MAKESILENT) -f third-party/CMakeFiles/flatcc_ep.dir/build.make third-party/CMakeFiles/flatcc_ep.dir/build
.PHONY : flatcc_ep/fast

#=============================================================================
# Target rules for targets named gflags_nothreads_static

# Build rule for target.
gflags_nothreads_static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gflags_nothreads_static
.PHONY : gflags_nothreads_static

# fast build rule for target.
gflags_nothreads_static/fast:
	$(MAKE) $(MAKESILENT) -f third-party/gflags/CMakeFiles/gflags_nothreads_static.dir/build.make third-party/gflags/CMakeFiles/gflags_nothreads_static.dir/build
.PHONY : gflags_nothreads_static/fast

#=============================================================================
# Target rules for targets named flatccrt

# Build rule for target.
flatccrt: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 flatccrt
.PHONY : flatccrt

# fast build rule for target.
flatccrt/fast:
	$(MAKE) $(MAKESILENT) -f third-party/flatcc/src/runtime/CMakeFiles/flatccrt.dir/build.make third-party/flatcc/src/runtime/CMakeFiles/flatccrt.dir/build
.PHONY : flatccrt/fast

#=============================================================================
# Target rules for targets named cpuinfo

# Build rule for target.
cpuinfo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cpuinfo
.PHONY : cpuinfo

# fast build rule for target.
cpuinfo/fast:
	$(MAKE) $(MAKESILENT) -f backends/xnnpack/third-party/cpuinfo/CMakeFiles/cpuinfo.dir/build.make backends/xnnpack/third-party/cpuinfo/CMakeFiles/cpuinfo.dir/build
.PHONY : cpuinfo/fast

#=============================================================================
# Target rules for targets named cpuinfo_internals

# Build rule for target.
cpuinfo_internals: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cpuinfo_internals
.PHONY : cpuinfo_internals

# fast build rule for target.
cpuinfo_internals/fast:
	$(MAKE) $(MAKESILENT) -f backends/xnnpack/third-party/cpuinfo/CMakeFiles/cpuinfo_internals.dir/build.make backends/xnnpack/third-party/cpuinfo/CMakeFiles/cpuinfo_internals.dir/build
.PHONY : cpuinfo_internals/fast

#=============================================================================
# Target rules for targets named pthreadpool

# Build rule for target.
pthreadpool: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pthreadpool
.PHONY : pthreadpool

# fast build rule for target.
pthreadpool/fast:
	$(MAKE) $(MAKESILENT) -f backends/xnnpack/third-party/pthreadpool/CMakeFiles/pthreadpool.dir/build.make backends/xnnpack/third-party/pthreadpool/CMakeFiles/pthreadpool.dir/build
.PHONY : pthreadpool/fast

#=============================================================================
# Target rules for targets named common_schema

# Build rule for target.
common_schema: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 common_schema
.PHONY : common_schema

# fast build rule for target.
common_schema/fast:
	$(MAKE) $(MAKESILENT) -f schema/CMakeFiles/common_schema.dir/build.make schema/CMakeFiles/common_schema.dir/build
.PHONY : common_schema/fast

#=============================================================================
# Target rules for targets named program_schema

# Build rule for target.
program_schema: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 program_schema
.PHONY : program_schema

# fast build rule for target.
program_schema/fast:
	$(MAKE) $(MAKESILENT) -f schema/CMakeFiles/program_schema.dir/build.make schema/CMakeFiles/program_schema.dir/build
.PHONY : program_schema/fast

#=============================================================================
# Target rules for targets named kernels_util_all_deps

# Build rule for target.
kernels_util_all_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 kernels_util_all_deps
.PHONY : kernels_util_all_deps

# fast build rule for target.
kernels_util_all_deps/fast:
	$(MAKE) $(MAKESILENT) -f kernels/portable/cpu/util/CMakeFiles/kernels_util_all_deps.dir/build.make kernels/portable/cpu/util/CMakeFiles/kernels_util_all_deps.dir/build
.PHONY : kernels_util_all_deps/fast

#=============================================================================
# Target rules for targets named portable_kernels

# Build rule for target.
portable_kernels: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 portable_kernels
.PHONY : portable_kernels

# fast build rule for target.
portable_kernels/fast:
	$(MAKE) $(MAKESILENT) -f kernels/portable/CMakeFiles/portable_kernels.dir/build.make kernels/portable/CMakeFiles/portable_kernels.dir/build
.PHONY : portable_kernels/fast

#=============================================================================
# Target rules for targets named portable_ops_lib

# Build rule for target.
portable_ops_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 portable_ops_lib
.PHONY : portable_ops_lib

# fast build rule for target.
portable_ops_lib/fast:
	$(MAKE) $(MAKESILENT) -f kernels/portable/CMakeFiles/portable_ops_lib.dir/build.make kernels/portable/CMakeFiles/portable_ops_lib.dir/build
.PHONY : portable_ops_lib/fast

#=============================================================================
# Target rules for targets named qnn_backend

# Build rule for target.
qnn_backend: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 qnn_backend
.PHONY : qnn_backend

# fast build rule for target.
qnn_backend/fast:
	$(MAKE) $(MAKESILENT) -f backends/qualcomm/CMakeFiles/qnn_backend.dir/build.make backends/qualcomm/CMakeFiles/qnn_backend.dir/build
.PHONY : qnn_backend/fast

#=============================================================================
# Target rules for targets named qnn_backend_cache

# Build rule for target.
qnn_backend_cache: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 qnn_backend_cache
.PHONY : qnn_backend_cache

# fast build rule for target.
qnn_backend_cache/fast:
	$(MAKE) $(MAKESILENT) -f backends/qualcomm/CMakeFiles/qnn_backend_cache.dir/build.make backends/qualcomm/CMakeFiles/qnn_backend_cache.dir/build
.PHONY : qnn_backend_cache/fast

#=============================================================================
# Target rules for targets named qnn_backend_options

# Build rule for target.
qnn_backend_options: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 qnn_backend_options
.PHONY : qnn_backend_options

# fast build rule for target.
qnn_backend_options/fast:
	$(MAKE) $(MAKESILENT) -f backends/qualcomm/CMakeFiles/qnn_backend_options.dir/build.make backends/qualcomm/CMakeFiles/qnn_backend_options.dir/build
.PHONY : qnn_backend_options/fast

#=============================================================================
# Target rules for targets named qnn_context

# Build rule for target.
qnn_context: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 qnn_context
.PHONY : qnn_context

# fast build rule for target.
qnn_context/fast:
	$(MAKE) $(MAKESILENT) -f backends/qualcomm/CMakeFiles/qnn_context.dir/build.make backends/qualcomm/CMakeFiles/qnn_context.dir/build
.PHONY : qnn_context/fast

#=============================================================================
# Target rules for targets named qnn_custom_protocol

# Build rule for target.
qnn_custom_protocol: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 qnn_custom_protocol
.PHONY : qnn_custom_protocol

# fast build rule for target.
qnn_custom_protocol/fast:
	$(MAKE) $(MAKESILENT) -f backends/qualcomm/CMakeFiles/qnn_custom_protocol.dir/build.make backends/qualcomm/CMakeFiles/qnn_custom_protocol.dir/build
.PHONY : qnn_custom_protocol/fast

#=============================================================================
# Target rules for targets named qnn_dlc_manager

# Build rule for target.
qnn_dlc_manager: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 qnn_dlc_manager
.PHONY : qnn_dlc_manager

# fast build rule for target.
qnn_dlc_manager/fast:
	$(MAKE) $(MAKESILENT) -f backends/qualcomm/CMakeFiles/qnn_dlc_manager.dir/build.make backends/qualcomm/CMakeFiles/qnn_dlc_manager.dir/build
.PHONY : qnn_dlc_manager/fast

#=============================================================================
# Target rules for targets named qnn_device

# Build rule for target.
qnn_device: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 qnn_device
.PHONY : qnn_device

# fast build rule for target.
qnn_device/fast:
	$(MAKE) $(MAKESILENT) -f backends/qualcomm/CMakeFiles/qnn_device.dir/build.make backends/qualcomm/CMakeFiles/qnn_device.dir/build
.PHONY : qnn_device/fast

#=============================================================================
# Target rules for targets named qnn_executorch_backend

# Build rule for target.
qnn_executorch_backend: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 qnn_executorch_backend
.PHONY : qnn_executorch_backend

# fast build rule for target.
qnn_executorch_backend/fast:
	$(MAKE) $(MAKESILENT) -f backends/qualcomm/CMakeFiles/qnn_executorch_backend.dir/build.make backends/qualcomm/CMakeFiles/qnn_executorch_backend.dir/build
.PHONY : qnn_executorch_backend/fast

#=============================================================================
# Target rules for targets named qnn_executorch_logging

# Build rule for target.
qnn_executorch_logging: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 qnn_executorch_logging
.PHONY : qnn_executorch_logging

# fast build rule for target.
qnn_executorch_logging/fast:
	$(MAKE) $(MAKESILENT) -f backends/qualcomm/CMakeFiles/qnn_executorch_logging.dir/build.make backends/qualcomm/CMakeFiles/qnn_executorch_logging.dir/build
.PHONY : qnn_executorch_logging/fast

#=============================================================================
# Target rules for targets named qnn_factory

# Build rule for target.
qnn_factory: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 qnn_factory
.PHONY : qnn_factory

# fast build rule for target.
qnn_factory/fast:
	$(MAKE) $(MAKESILENT) -f backends/qualcomm/CMakeFiles/qnn_factory.dir/build.make backends/qualcomm/CMakeFiles/qnn_factory.dir/build
.PHONY : qnn_factory/fast

#=============================================================================
# Target rules for targets named qnn_backend_unified_registry

# Build rule for target.
qnn_backend_unified_registry: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 qnn_backend_unified_registry
.PHONY : qnn_backend_unified_registry

# fast build rule for target.
qnn_backend_unified_registry/fast:
	$(MAKE) $(MAKESILENT) -f backends/qualcomm/CMakeFiles/qnn_backend_unified_registry.dir/build.make backends/qualcomm/CMakeFiles/qnn_backend_unified_registry.dir/build
.PHONY : qnn_backend_unified_registry/fast

#=============================================================================
# Target rules for targets named qnn_graph

# Build rule for target.
qnn_graph: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 qnn_graph
.PHONY : qnn_graph

# fast build rule for target.
qnn_graph/fast:
	$(MAKE) $(MAKESILENT) -f backends/qualcomm/CMakeFiles/qnn_graph.dir/build.make backends/qualcomm/CMakeFiles/qnn_graph.dir/build
.PHONY : qnn_graph/fast

#=============================================================================
# Target rules for targets named qnn_implementation

# Build rule for target.
qnn_implementation: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 qnn_implementation
.PHONY : qnn_implementation

# fast build rule for target.
qnn_implementation/fast:
	$(MAKE) $(MAKESILENT) -f backends/qualcomm/CMakeFiles/qnn_implementation.dir/build.make backends/qualcomm/CMakeFiles/qnn_implementation.dir/build
.PHONY : qnn_implementation/fast

#=============================================================================
# Target rules for targets named qnn_logger

# Build rule for target.
qnn_logger: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 qnn_logger
.PHONY : qnn_logger

# fast build rule for target.
qnn_logger/fast:
	$(MAKE) $(MAKESILENT) -f backends/qualcomm/CMakeFiles/qnn_logger.dir/build.make backends/qualcomm/CMakeFiles/qnn_logger.dir/build
.PHONY : qnn_logger/fast

#=============================================================================
# Target rules for targets named qnn_manager

# Build rule for target.
qnn_manager: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 qnn_manager
.PHONY : qnn_manager

# fast build rule for target.
qnn_manager/fast:
	$(MAKE) $(MAKESILENT) -f backends/qualcomm/CMakeFiles/qnn_manager.dir/build.make backends/qualcomm/CMakeFiles/qnn_manager.dir/build
.PHONY : qnn_manager/fast

#=============================================================================
# Target rules for targets named qnn_mem_manager

# Build rule for target.
qnn_mem_manager: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 qnn_mem_manager
.PHONY : qnn_mem_manager

# fast build rule for target.
qnn_mem_manager/fast:
	$(MAKE) $(MAKESILENT) -f backends/qualcomm/CMakeFiles/qnn_mem_manager.dir/build.make backends/qualcomm/CMakeFiles/qnn_mem_manager.dir/build
.PHONY : qnn_mem_manager/fast

#=============================================================================
# Target rules for targets named qnn_op_package_manager

# Build rule for target.
qnn_op_package_manager: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 qnn_op_package_manager
.PHONY : qnn_op_package_manager

# fast build rule for target.
qnn_op_package_manager/fast:
	$(MAKE) $(MAKESILENT) -f backends/qualcomm/CMakeFiles/qnn_op_package_manager.dir/build.make backends/qualcomm/CMakeFiles/qnn_op_package_manager.dir/build
.PHONY : qnn_op_package_manager/fast

#=============================================================================
# Target rules for targets named qnn_profiler

# Build rule for target.
qnn_profiler: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 qnn_profiler
.PHONY : qnn_profiler

# fast build rule for target.
qnn_profiler/fast:
	$(MAKE) $(MAKESILENT) -f backends/qualcomm/CMakeFiles/qnn_profiler.dir/build.make backends/qualcomm/CMakeFiles/qnn_profiler.dir/build
.PHONY : qnn_profiler/fast

#=============================================================================
# Target rules for targets named qnn_schema

# Build rule for target.
qnn_schema: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 qnn_schema
.PHONY : qnn_schema

# fast build rule for target.
qnn_schema/fast:
	$(MAKE) $(MAKESILENT) -f backends/qualcomm/CMakeFiles/qnn_schema.dir/build.make backends/qualcomm/CMakeFiles/qnn_schema.dir/build
.PHONY : qnn_schema/fast

#=============================================================================
# Target rules for targets named qnn_sys_implementation

# Build rule for target.
qnn_sys_implementation: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 qnn_sys_implementation
.PHONY : qnn_sys_implementation

# fast build rule for target.
qnn_sys_implementation/fast:
	$(MAKE) $(MAKESILENT) -f backends/qualcomm/CMakeFiles/qnn_sys_implementation.dir/build.make backends/qualcomm/CMakeFiles/qnn_sys_implementation.dir/build
.PHONY : qnn_sys_implementation/fast

#=============================================================================
# Target rules for targets named shared_buffer

# Build rule for target.
shared_buffer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 shared_buffer
.PHONY : shared_buffer

# fast build rule for target.
shared_buffer/fast:
	$(MAKE) $(MAKESILENT) -f backends/qualcomm/CMakeFiles/shared_buffer.dir/build.make backends/qualcomm/CMakeFiles/shared_buffer.dir/build
.PHONY : shared_buffer/fast

#=============================================================================
# Target rules for targets named wrappers

# Build rule for target.
wrappers: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 wrappers
.PHONY : wrappers

# fast build rule for target.
wrappers/fast:
	$(MAKE) $(MAKESILENT) -f backends/qualcomm/CMakeFiles/wrappers.dir/build.make backends/qualcomm/CMakeFiles/wrappers.dir/build
.PHONY : wrappers/fast

#=============================================================================
# Target rules for targets named xnnpack_schema

# Build rule for target.
xnnpack_schema: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 xnnpack_schema
.PHONY : xnnpack_schema

# fast build rule for target.
xnnpack_schema/fast:
	$(MAKE) $(MAKESILENT) -f backends/xnnpack/CMakeFiles/xnnpack_schema.dir/build.make backends/xnnpack/CMakeFiles/xnnpack_schema.dir/build
.PHONY : xnnpack_schema/fast

#=============================================================================
# Target rules for targets named xnnpack_backend

# Build rule for target.
xnnpack_backend: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 xnnpack_backend
.PHONY : xnnpack_backend

# fast build rule for target.
xnnpack_backend/fast:
	$(MAKE) $(MAKESILENT) -f backends/xnnpack/CMakeFiles/xnnpack_backend.dir/build.make backends/xnnpack/CMakeFiles/xnnpack_backend.dir/build
.PHONY : xnnpack_backend/fast

#=============================================================================
# Target rules for targets named xnnpack-sanitizers

# Build rule for target.
xnnpack-sanitizers: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 xnnpack-sanitizers
.PHONY : xnnpack-sanitizers

# fast build rule for target.
xnnpack-sanitizers/fast:
	$(MAKE) $(MAKESILENT) -f backends/xnnpack/third-party/XNNPACK/CMakeFiles/xnnpack-sanitizers.dir/build.make backends/xnnpack/third-party/XNNPACK/CMakeFiles/xnnpack-sanitizers.dir/build
.PHONY : xnnpack-sanitizers/fast

#=============================================================================
# Target rules for targets named xnnpack-microkernels-prod

# Build rule for target.
xnnpack-microkernels-prod: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 xnnpack-microkernels-prod
.PHONY : xnnpack-microkernels-prod

# fast build rule for target.
xnnpack-microkernels-prod/fast:
	$(MAKE) $(MAKESILENT) -f backends/xnnpack/third-party/XNNPACK/CMakeFiles/xnnpack-microkernels-prod.dir/build.make backends/xnnpack/third-party/XNNPACK/CMakeFiles/xnnpack-microkernels-prod.dir/build
.PHONY : xnnpack-microkernels-prod/fast

#=============================================================================
# Target rules for targets named xnnpack-hardware-config

# Build rule for target.
xnnpack-hardware-config: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 xnnpack-hardware-config
.PHONY : xnnpack-hardware-config

# fast build rule for target.
xnnpack-hardware-config/fast:
	$(MAKE) $(MAKESILENT) -f backends/xnnpack/third-party/XNNPACK/CMakeFiles/xnnpack-hardware-config.dir/build.make backends/xnnpack/third-party/XNNPACK/CMakeFiles/xnnpack-hardware-config.dir/build
.PHONY : xnnpack-hardware-config/fast

#=============================================================================
# Target rules for targets named xnnpack-indirection

# Build rule for target.
xnnpack-indirection: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 xnnpack-indirection
.PHONY : xnnpack-indirection

# fast build rule for target.
xnnpack-indirection/fast:
	$(MAKE) $(MAKESILENT) -f backends/xnnpack/third-party/XNNPACK/CMakeFiles/xnnpack-indirection.dir/build.make backends/xnnpack/third-party/XNNPACK/CMakeFiles/xnnpack-indirection.dir/build
.PHONY : xnnpack-indirection/fast

#=============================================================================
# Target rules for targets named xnnpack-logging

# Build rule for target.
xnnpack-logging: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 xnnpack-logging
.PHONY : xnnpack-logging

# fast build rule for target.
xnnpack-logging/fast:
	$(MAKE) $(MAKESILENT) -f backends/xnnpack/third-party/XNNPACK/CMakeFiles/xnnpack-logging.dir/build.make backends/xnnpack/third-party/XNNPACK/CMakeFiles/xnnpack-logging.dir/build
.PHONY : xnnpack-logging/fast

#=============================================================================
# Target rules for targets named xnnpack-microparams-init

# Build rule for target.
xnnpack-microparams-init: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 xnnpack-microparams-init
.PHONY : xnnpack-microparams-init

# fast build rule for target.
xnnpack-microparams-init/fast:
	$(MAKE) $(MAKESILENT) -f backends/xnnpack/third-party/XNNPACK/CMakeFiles/xnnpack-microparams-init.dir/build.make backends/xnnpack/third-party/XNNPACK/CMakeFiles/xnnpack-microparams-init.dir/build
.PHONY : xnnpack-microparams-init/fast

#=============================================================================
# Target rules for targets named xnnpack-normalization

# Build rule for target.
xnnpack-normalization: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 xnnpack-normalization
.PHONY : xnnpack-normalization

# fast build rule for target.
xnnpack-normalization/fast:
	$(MAKE) $(MAKESILENT) -f backends/xnnpack/third-party/XNNPACK/CMakeFiles/xnnpack-normalization.dir/build.make backends/xnnpack/third-party/XNNPACK/CMakeFiles/xnnpack-normalization.dir/build
.PHONY : xnnpack-normalization/fast

#=============================================================================
# Target rules for targets named xnnpack-pack-lh

# Build rule for target.
xnnpack-pack-lh: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 xnnpack-pack-lh
.PHONY : xnnpack-pack-lh

# fast build rule for target.
xnnpack-pack-lh/fast:
	$(MAKE) $(MAKESILENT) -f backends/xnnpack/third-party/XNNPACK/CMakeFiles/xnnpack-pack-lh.dir/build.make backends/xnnpack/third-party/XNNPACK/CMakeFiles/xnnpack-pack-lh.dir/build
.PHONY : xnnpack-pack-lh/fast

#=============================================================================
# Target rules for targets named xnnpack-packing

# Build rule for target.
xnnpack-packing: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 xnnpack-packing
.PHONY : xnnpack-packing

# fast build rule for target.
xnnpack-packing/fast:
	$(MAKE) $(MAKESILENT) -f backends/xnnpack/third-party/XNNPACK/CMakeFiles/xnnpack-packing.dir/build.make backends/xnnpack/third-party/XNNPACK/CMakeFiles/xnnpack-packing.dir/build
.PHONY : xnnpack-packing/fast

#=============================================================================
# Target rules for targets named xnnpack-allocator

# Build rule for target.
xnnpack-allocator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 xnnpack-allocator
.PHONY : xnnpack-allocator

# fast build rule for target.
xnnpack-allocator/fast:
	$(MAKE) $(MAKESILENT) -f backends/xnnpack/third-party/XNNPACK/CMakeFiles/xnnpack-allocator.dir/build.make backends/xnnpack/third-party/XNNPACK/CMakeFiles/xnnpack-allocator.dir/build
.PHONY : xnnpack-allocator/fast

#=============================================================================
# Target rules for targets named xnnpack-cache

# Build rule for target.
xnnpack-cache: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 xnnpack-cache
.PHONY : xnnpack-cache

# fast build rule for target.
xnnpack-cache/fast:
	$(MAKE) $(MAKESILENT) -f backends/xnnpack/third-party/XNNPACK/CMakeFiles/xnnpack-cache.dir/build.make backends/xnnpack/third-party/XNNPACK/CMakeFiles/xnnpack-cache.dir/build
.PHONY : xnnpack-cache/fast

#=============================================================================
# Target rules for targets named xnnpack-datatype

# Build rule for target.
xnnpack-datatype: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 xnnpack-datatype
.PHONY : xnnpack-datatype

# fast build rule for target.
xnnpack-datatype/fast:
	$(MAKE) $(MAKESILENT) -f backends/xnnpack/third-party/XNNPACK/CMakeFiles/xnnpack-datatype.dir/build.make backends/xnnpack/third-party/XNNPACK/CMakeFiles/xnnpack-datatype.dir/build
.PHONY : xnnpack-datatype/fast

#=============================================================================
# Target rules for targets named xnnpack-operator-delete

# Build rule for target.
xnnpack-operator-delete: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 xnnpack-operator-delete
.PHONY : xnnpack-operator-delete

# fast build rule for target.
xnnpack-operator-delete/fast:
	$(MAKE) $(MAKESILENT) -f backends/xnnpack/third-party/XNNPACK/CMakeFiles/xnnpack-operator-delete.dir/build.make backends/xnnpack/third-party/XNNPACK/CMakeFiles/xnnpack-operator-delete.dir/build
.PHONY : xnnpack-operator-delete/fast

#=============================================================================
# Target rules for targets named xnnpack-fingerprint-id

# Build rule for target.
xnnpack-fingerprint-id: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 xnnpack-fingerprint-id
.PHONY : xnnpack-fingerprint-id

# fast build rule for target.
xnnpack-fingerprint-id/fast:
	$(MAKE) $(MAKESILENT) -f backends/xnnpack/third-party/XNNPACK/CMakeFiles/xnnpack-fingerprint-id.dir/build.make backends/xnnpack/third-party/XNNPACK/CMakeFiles/xnnpack-fingerprint-id.dir/build
.PHONY : xnnpack-fingerprint-id/fast

#=============================================================================
# Target rules for targets named xnnpack-fingerprint-cache

# Build rule for target.
xnnpack-fingerprint-cache: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 xnnpack-fingerprint-cache
.PHONY : xnnpack-fingerprint-cache

# fast build rule for target.
xnnpack-fingerprint-cache/fast:
	$(MAKE) $(MAKESILENT) -f backends/xnnpack/third-party/XNNPACK/CMakeFiles/xnnpack-fingerprint-cache.dir/build.make backends/xnnpack/third-party/XNNPACK/CMakeFiles/xnnpack-fingerprint-cache.dir/build
.PHONY : xnnpack-fingerprint-cache/fast

#=============================================================================
# Target rules for targets named xnnpack-fingerprint-check

# Build rule for target.
xnnpack-fingerprint-check: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 xnnpack-fingerprint-check
.PHONY : xnnpack-fingerprint-check

# fast build rule for target.
xnnpack-fingerprint-check/fast:
	$(MAKE) $(MAKESILENT) -f backends/xnnpack/third-party/XNNPACK/CMakeFiles/xnnpack-fingerprint-check.dir/build.make backends/xnnpack/third-party/XNNPACK/CMakeFiles/xnnpack-fingerprint-check.dir/build
.PHONY : xnnpack-fingerprint-check/fast

#=============================================================================
# Target rules for targets named xnnpack-memory

# Build rule for target.
xnnpack-memory: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 xnnpack-memory
.PHONY : xnnpack-memory

# fast build rule for target.
xnnpack-memory/fast:
	$(MAKE) $(MAKESILENT) -f backends/xnnpack/third-party/XNNPACK/CMakeFiles/xnnpack-memory.dir/build.make backends/xnnpack/third-party/XNNPACK/CMakeFiles/xnnpack-memory.dir/build
.PHONY : xnnpack-memory/fast

#=============================================================================
# Target rules for targets named xnnpack-microkernel-utils

# Build rule for target.
xnnpack-microkernel-utils: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 xnnpack-microkernel-utils
.PHONY : xnnpack-microkernel-utils

# fast build rule for target.
xnnpack-microkernel-utils/fast:
	$(MAKE) $(MAKESILENT) -f backends/xnnpack/third-party/XNNPACK/CMakeFiles/xnnpack-microkernel-utils.dir/build.make backends/xnnpack/third-party/XNNPACK/CMakeFiles/xnnpack-microkernel-utils.dir/build
.PHONY : xnnpack-microkernel-utils/fast

#=============================================================================
# Target rules for targets named xnnpack-mutex

# Build rule for target.
xnnpack-mutex: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 xnnpack-mutex
.PHONY : xnnpack-mutex

# fast build rule for target.
xnnpack-mutex/fast:
	$(MAKE) $(MAKESILENT) -f backends/xnnpack/third-party/XNNPACK/CMakeFiles/xnnpack-mutex.dir/build.make backends/xnnpack/third-party/XNNPACK/CMakeFiles/xnnpack-mutex.dir/build
.PHONY : xnnpack-mutex/fast

#=============================================================================
# Target rules for targets named xnnpack-operators

# Build rule for target.
xnnpack-operators: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 xnnpack-operators
.PHONY : xnnpack-operators

# fast build rule for target.
xnnpack-operators/fast:
	$(MAKE) $(MAKESILENT) -f backends/xnnpack/third-party/XNNPACK/CMakeFiles/xnnpack-operators.dir/build.make backends/xnnpack/third-party/XNNPACK/CMakeFiles/xnnpack-operators.dir/build
.PHONY : xnnpack-operators/fast

#=============================================================================
# Target rules for targets named xnnpack-operator-run

# Build rule for target.
xnnpack-operator-run: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 xnnpack-operator-run
.PHONY : xnnpack-operator-run

# fast build rule for target.
xnnpack-operator-run/fast:
	$(MAKE) $(MAKESILENT) -f backends/xnnpack/third-party/XNNPACK/CMakeFiles/xnnpack-operator-run.dir/build.make backends/xnnpack/third-party/XNNPACK/CMakeFiles/xnnpack-operator-run.dir/build
.PHONY : xnnpack-operator-run/fast

#=============================================================================
# Target rules for targets named xnnpack-operator-utils

# Build rule for target.
xnnpack-operator-utils: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 xnnpack-operator-utils
.PHONY : xnnpack-operator-utils

# fast build rule for target.
xnnpack-operator-utils/fast:
	$(MAKE) $(MAKESILENT) -f backends/xnnpack/third-party/XNNPACK/CMakeFiles/xnnpack-operator-utils.dir/build.make backends/xnnpack/third-party/XNNPACK/CMakeFiles/xnnpack-operator-utils.dir/build
.PHONY : xnnpack-operator-utils/fast

#=============================================================================
# Target rules for targets named xnnpack-reference-ukernels

# Build rule for target.
xnnpack-reference-ukernels: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 xnnpack-reference-ukernels
.PHONY : xnnpack-reference-ukernels

# fast build rule for target.
xnnpack-reference-ukernels/fast:
	$(MAKE) $(MAKESILENT) -f backends/xnnpack/third-party/XNNPACK/CMakeFiles/xnnpack-reference-ukernels.dir/build.make backends/xnnpack/third-party/XNNPACK/CMakeFiles/xnnpack-reference-ukernels.dir/build
.PHONY : xnnpack-reference-ukernels/fast

#=============================================================================
# Target rules for targets named xnnpack-subgraph

# Build rule for target.
xnnpack-subgraph: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 xnnpack-subgraph
.PHONY : xnnpack-subgraph

# fast build rule for target.
xnnpack-subgraph/fast:
	$(MAKE) $(MAKESILENT) -f backends/xnnpack/third-party/XNNPACK/CMakeFiles/xnnpack-subgraph.dir/build.make backends/xnnpack/third-party/XNNPACK/CMakeFiles/xnnpack-subgraph.dir/build
.PHONY : xnnpack-subgraph/fast

#=============================================================================
# Target rules for targets named XNNPACK

# Build rule for target.
XNNPACK: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 XNNPACK
.PHONY : XNNPACK

# fast build rule for target.
XNNPACK/fast:
	$(MAKE) $(MAKESILENT) -f backends/xnnpack/third-party/XNNPACK/CMakeFiles/XNNPACK.dir/build.make backends/xnnpack/third-party/XNNPACK/CMakeFiles/XNNPACK.dir/build
.PHONY : XNNPACK/fast

#=============================================================================
# Target rules for targets named kleidiai

# Build rule for target.
kleidiai: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 kleidiai
.PHONY : kleidiai

# fast build rule for target.
kleidiai/fast:
	$(MAKE) $(MAKESILENT) -f kleidiai/CMakeFiles/kleidiai.dir/build.make kleidiai/CMakeFiles/kleidiai.dir/build
.PHONY : kleidiai/fast

#=============================================================================
# Target rules for targets named extension_data_loader

# Build rule for target.
extension_data_loader: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 extension_data_loader
.PHONY : extension_data_loader

# fast build rule for target.
extension_data_loader/fast:
	$(MAKE) $(MAKESILENT) -f extension/data_loader/CMakeFiles/extension_data_loader.dir/build.make extension/data_loader/CMakeFiles/extension_data_loader.dir/build
.PHONY : extension_data_loader/fast

#=============================================================================
# Target rules for targets named extension_evalue_util

# Build rule for target.
extension_evalue_util: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 extension_evalue_util
.PHONY : extension_evalue_util

# fast build rule for target.
extension_evalue_util/fast:
	$(MAKE) $(MAKESILENT) -f extension/evalue_util/CMakeFiles/extension_evalue_util.dir/build.make extension/evalue_util/CMakeFiles/extension_evalue_util.dir/build
.PHONY : extension_evalue_util/fast

#=============================================================================
# Target rules for targets named extension_flat_tensor

# Build rule for target.
extension_flat_tensor: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 extension_flat_tensor
.PHONY : extension_flat_tensor

# fast build rule for target.
extension_flat_tensor/fast:
	$(MAKE) $(MAKESILENT) -f extension/flat_tensor/CMakeFiles/extension_flat_tensor.dir/build.make extension/flat_tensor/CMakeFiles/extension_flat_tensor.dir/build
.PHONY : extension_flat_tensor/fast

#=============================================================================
# Target rules for targets named scalar_type_schema

# Build rule for target.
scalar_type_schema: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 scalar_type_schema
.PHONY : scalar_type_schema

# fast build rule for target.
scalar_type_schema/fast:
	$(MAKE) $(MAKESILENT) -f extension/flat_tensor/serialize/CMakeFiles/scalar_type_schema.dir/build.make extension/flat_tensor/serialize/CMakeFiles/scalar_type_schema.dir/build
.PHONY : scalar_type_schema/fast

#=============================================================================
# Target rules for targets named flat_tensor_schema

# Build rule for target.
flat_tensor_schema: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 flat_tensor_schema
.PHONY : flat_tensor_schema

# fast build rule for target.
flat_tensor_schema/fast:
	$(MAKE) $(MAKESILENT) -f extension/flat_tensor/serialize/CMakeFiles/flat_tensor_schema.dir/build.make extension/flat_tensor/serialize/CMakeFiles/flat_tensor_schema.dir/build
.PHONY : flat_tensor_schema/fast

#=============================================================================
# Target rules for targets named extension_runner_util

# Build rule for target.
extension_runner_util: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 extension_runner_util
.PHONY : extension_runner_util

# fast build rule for target.
extension_runner_util/fast:
	$(MAKE) $(MAKESILENT) -f extension/runner_util/CMakeFiles/extension_runner_util.dir/build.make extension/runner_util/CMakeFiles/extension_runner_util.dir/build
.PHONY : extension_runner_util/fast

#=============================================================================
# Target rules for targets named extension_tensor

# Build rule for target.
extension_tensor: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 extension_tensor
.PHONY : extension_tensor

# fast build rule for target.
extension_tensor/fast:
	$(MAKE) $(MAKESILENT) -f extension/tensor/CMakeFiles/extension_tensor.dir/build.make extension/tensor/CMakeFiles/extension_tensor.dir/build
.PHONY : extension_tensor/fast

#=============================================================================
# Target rules for targets named extension_threadpool

# Build rule for target.
extension_threadpool: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 extension_threadpool
.PHONY : extension_threadpool

# fast build rule for target.
extension_threadpool/fast:
	$(MAKE) $(MAKESILENT) -f extension/threadpool/CMakeFiles/extension_threadpool.dir/build.make extension/threadpool/CMakeFiles/extension_threadpool.dir/build
.PHONY : extension_threadpool/fast

examples/portable/executor_runner/executor_runner.o: examples/portable/executor_runner/executor_runner.cpp.o
.PHONY : examples/portable/executor_runner/executor_runner.o

# target to build an object file
examples/portable/executor_runner/executor_runner.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executor_runner.dir/build.make CMakeFiles/executor_runner.dir/examples/portable/executor_runner/executor_runner.cpp.o
.PHONY : examples/portable/executor_runner/executor_runner.cpp.o

examples/portable/executor_runner/executor_runner.i: examples/portable/executor_runner/executor_runner.cpp.i
.PHONY : examples/portable/executor_runner/executor_runner.i

# target to preprocess a source file
examples/portable/executor_runner/executor_runner.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executor_runner.dir/build.make CMakeFiles/executor_runner.dir/examples/portable/executor_runner/executor_runner.cpp.i
.PHONY : examples/portable/executor_runner/executor_runner.cpp.i

examples/portable/executor_runner/executor_runner.s: examples/portable/executor_runner/executor_runner.cpp.s
.PHONY : examples/portable/executor_runner/executor_runner.s

# target to generate assembly for a file
examples/portable/executor_runner/executor_runner.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executor_runner.dir/build.make CMakeFiles/executor_runner.dir/examples/portable/executor_runner/executor_runner.cpp.s
.PHONY : examples/portable/executor_runner/executor_runner.cpp.s

extension/data_loader/file_data_loader.o: extension/data_loader/file_data_loader.cpp.o
.PHONY : extension/data_loader/file_data_loader.o

# target to build an object file
extension/data_loader/file_data_loader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executor_runner.dir/build.make CMakeFiles/executor_runner.dir/extension/data_loader/file_data_loader.cpp.o
.PHONY : extension/data_loader/file_data_loader.cpp.o

extension/data_loader/file_data_loader.i: extension/data_loader/file_data_loader.cpp.i
.PHONY : extension/data_loader/file_data_loader.i

# target to preprocess a source file
extension/data_loader/file_data_loader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executor_runner.dir/build.make CMakeFiles/executor_runner.dir/extension/data_loader/file_data_loader.cpp.i
.PHONY : extension/data_loader/file_data_loader.cpp.i

extension/data_loader/file_data_loader.s: extension/data_loader/file_data_loader.cpp.s
.PHONY : extension/data_loader/file_data_loader.s

# target to generate assembly for a file
extension/data_loader/file_data_loader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executor_runner.dir/build.make CMakeFiles/executor_runner.dir/extension/data_loader/file_data_loader.cpp.s
.PHONY : extension/data_loader/file_data_loader.cpp.s

kernels/prim_ops/et_copy_index.o: kernels/prim_ops/et_copy_index.cpp.o
.PHONY : kernels/prim_ops/et_copy_index.o

# target to build an object file
kernels/prim_ops/et_copy_index.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executorch.dir/build.make CMakeFiles/executorch.dir/kernels/prim_ops/et_copy_index.cpp.o
.PHONY : kernels/prim_ops/et_copy_index.cpp.o

kernels/prim_ops/et_copy_index.i: kernels/prim_ops/et_copy_index.cpp.i
.PHONY : kernels/prim_ops/et_copy_index.i

# target to preprocess a source file
kernels/prim_ops/et_copy_index.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executorch.dir/build.make CMakeFiles/executorch.dir/kernels/prim_ops/et_copy_index.cpp.i
.PHONY : kernels/prim_ops/et_copy_index.cpp.i

kernels/prim_ops/et_copy_index.s: kernels/prim_ops/et_copy_index.cpp.s
.PHONY : kernels/prim_ops/et_copy_index.s

# target to generate assembly for a file
kernels/prim_ops/et_copy_index.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executorch.dir/build.make CMakeFiles/executorch.dir/kernels/prim_ops/et_copy_index.cpp.s
.PHONY : kernels/prim_ops/et_copy_index.cpp.s

kernels/prim_ops/et_view.o: kernels/prim_ops/et_view.cpp.o
.PHONY : kernels/prim_ops/et_view.o

# target to build an object file
kernels/prim_ops/et_view.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executorch.dir/build.make CMakeFiles/executorch.dir/kernels/prim_ops/et_view.cpp.o
.PHONY : kernels/prim_ops/et_view.cpp.o

kernels/prim_ops/et_view.i: kernels/prim_ops/et_view.cpp.i
.PHONY : kernels/prim_ops/et_view.i

# target to preprocess a source file
kernels/prim_ops/et_view.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executorch.dir/build.make CMakeFiles/executorch.dir/kernels/prim_ops/et_view.cpp.i
.PHONY : kernels/prim_ops/et_view.cpp.i

kernels/prim_ops/et_view.s: kernels/prim_ops/et_view.cpp.s
.PHONY : kernels/prim_ops/et_view.s

# target to generate assembly for a file
kernels/prim_ops/et_view.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executorch.dir/build.make CMakeFiles/executorch.dir/kernels/prim_ops/et_view.cpp.s
.PHONY : kernels/prim_ops/et_view.cpp.s

kernels/prim_ops/register_prim_ops.o: kernels/prim_ops/register_prim_ops.cpp.o
.PHONY : kernels/prim_ops/register_prim_ops.o

# target to build an object file
kernels/prim_ops/register_prim_ops.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executorch.dir/build.make CMakeFiles/executorch.dir/kernels/prim_ops/register_prim_ops.cpp.o
.PHONY : kernels/prim_ops/register_prim_ops.cpp.o

kernels/prim_ops/register_prim_ops.i: kernels/prim_ops/register_prim_ops.cpp.i
.PHONY : kernels/prim_ops/register_prim_ops.i

# target to preprocess a source file
kernels/prim_ops/register_prim_ops.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executorch.dir/build.make CMakeFiles/executorch.dir/kernels/prim_ops/register_prim_ops.cpp.i
.PHONY : kernels/prim_ops/register_prim_ops.cpp.i

kernels/prim_ops/register_prim_ops.s: kernels/prim_ops/register_prim_ops.cpp.s
.PHONY : kernels/prim_ops/register_prim_ops.s

# target to generate assembly for a file
kernels/prim_ops/register_prim_ops.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executorch.dir/build.make CMakeFiles/executorch.dir/kernels/prim_ops/register_prim_ops.cpp.s
.PHONY : kernels/prim_ops/register_prim_ops.cpp.s

runtime/backend/interface.o: runtime/backend/interface.cpp.o
.PHONY : runtime/backend/interface.o

# target to build an object file
runtime/backend/interface.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executorch_core.dir/build.make CMakeFiles/executorch_core.dir/runtime/backend/interface.cpp.o
.PHONY : runtime/backend/interface.cpp.o

runtime/backend/interface.i: runtime/backend/interface.cpp.i
.PHONY : runtime/backend/interface.i

# target to preprocess a source file
runtime/backend/interface.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executorch_core.dir/build.make CMakeFiles/executorch_core.dir/runtime/backend/interface.cpp.i
.PHONY : runtime/backend/interface.cpp.i

runtime/backend/interface.s: runtime/backend/interface.cpp.s
.PHONY : runtime/backend/interface.s

# target to generate assembly for a file
runtime/backend/interface.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executorch_core.dir/build.make CMakeFiles/executorch_core.dir/runtime/backend/interface.cpp.s
.PHONY : runtime/backend/interface.cpp.s

runtime/core/evalue.o: runtime/core/evalue.cpp.o
.PHONY : runtime/core/evalue.o

# target to build an object file
runtime/core/evalue.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executorch_core.dir/build.make CMakeFiles/executorch_core.dir/runtime/core/evalue.cpp.o
.PHONY : runtime/core/evalue.cpp.o

runtime/core/evalue.i: runtime/core/evalue.cpp.i
.PHONY : runtime/core/evalue.i

# target to preprocess a source file
runtime/core/evalue.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executorch_core.dir/build.make CMakeFiles/executorch_core.dir/runtime/core/evalue.cpp.i
.PHONY : runtime/core/evalue.cpp.i

runtime/core/evalue.s: runtime/core/evalue.cpp.s
.PHONY : runtime/core/evalue.s

# target to generate assembly for a file
runtime/core/evalue.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executorch_core.dir/build.make CMakeFiles/executorch_core.dir/runtime/core/evalue.cpp.s
.PHONY : runtime/core/evalue.cpp.s

runtime/core/exec_aten/util/tensor_shape_to_c_string.o: runtime/core/exec_aten/util/tensor_shape_to_c_string.cpp.o
.PHONY : runtime/core/exec_aten/util/tensor_shape_to_c_string.o

# target to build an object file
runtime/core/exec_aten/util/tensor_shape_to_c_string.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executorch_core.dir/build.make CMakeFiles/executorch_core.dir/runtime/core/exec_aten/util/tensor_shape_to_c_string.cpp.o
.PHONY : runtime/core/exec_aten/util/tensor_shape_to_c_string.cpp.o

runtime/core/exec_aten/util/tensor_shape_to_c_string.i: runtime/core/exec_aten/util/tensor_shape_to_c_string.cpp.i
.PHONY : runtime/core/exec_aten/util/tensor_shape_to_c_string.i

# target to preprocess a source file
runtime/core/exec_aten/util/tensor_shape_to_c_string.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executorch_core.dir/build.make CMakeFiles/executorch_core.dir/runtime/core/exec_aten/util/tensor_shape_to_c_string.cpp.i
.PHONY : runtime/core/exec_aten/util/tensor_shape_to_c_string.cpp.i

runtime/core/exec_aten/util/tensor_shape_to_c_string.s: runtime/core/exec_aten/util/tensor_shape_to_c_string.cpp.s
.PHONY : runtime/core/exec_aten/util/tensor_shape_to_c_string.s

# target to generate assembly for a file
runtime/core/exec_aten/util/tensor_shape_to_c_string.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executorch_core.dir/build.make CMakeFiles/executorch_core.dir/runtime/core/exec_aten/util/tensor_shape_to_c_string.cpp.s
.PHONY : runtime/core/exec_aten/util/tensor_shape_to_c_string.cpp.s

runtime/core/exec_aten/util/tensor_util_portable.o: runtime/core/exec_aten/util/tensor_util_portable.cpp.o
.PHONY : runtime/core/exec_aten/util/tensor_util_portable.o

# target to build an object file
runtime/core/exec_aten/util/tensor_util_portable.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executorch_core.dir/build.make CMakeFiles/executorch_core.dir/runtime/core/exec_aten/util/tensor_util_portable.cpp.o
.PHONY : runtime/core/exec_aten/util/tensor_util_portable.cpp.o

runtime/core/exec_aten/util/tensor_util_portable.i: runtime/core/exec_aten/util/tensor_util_portable.cpp.i
.PHONY : runtime/core/exec_aten/util/tensor_util_portable.i

# target to preprocess a source file
runtime/core/exec_aten/util/tensor_util_portable.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executorch_core.dir/build.make CMakeFiles/executorch_core.dir/runtime/core/exec_aten/util/tensor_util_portable.cpp.i
.PHONY : runtime/core/exec_aten/util/tensor_util_portable.cpp.i

runtime/core/exec_aten/util/tensor_util_portable.s: runtime/core/exec_aten/util/tensor_util_portable.cpp.s
.PHONY : runtime/core/exec_aten/util/tensor_util_portable.s

# target to generate assembly for a file
runtime/core/exec_aten/util/tensor_util_portable.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executorch_core.dir/build.make CMakeFiles/executorch_core.dir/runtime/core/exec_aten/util/tensor_util_portable.cpp.s
.PHONY : runtime/core/exec_aten/util/tensor_util_portable.cpp.s

runtime/core/portable_type/tensor_impl.o: runtime/core/portable_type/tensor_impl.cpp.o
.PHONY : runtime/core/portable_type/tensor_impl.o

# target to build an object file
runtime/core/portable_type/tensor_impl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executorch_core.dir/build.make CMakeFiles/executorch_core.dir/runtime/core/portable_type/tensor_impl.cpp.o
.PHONY : runtime/core/portable_type/tensor_impl.cpp.o

runtime/core/portable_type/tensor_impl.i: runtime/core/portable_type/tensor_impl.cpp.i
.PHONY : runtime/core/portable_type/tensor_impl.i

# target to preprocess a source file
runtime/core/portable_type/tensor_impl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executorch_core.dir/build.make CMakeFiles/executorch_core.dir/runtime/core/portable_type/tensor_impl.cpp.i
.PHONY : runtime/core/portable_type/tensor_impl.cpp.i

runtime/core/portable_type/tensor_impl.s: runtime/core/portable_type/tensor_impl.cpp.s
.PHONY : runtime/core/portable_type/tensor_impl.s

# target to generate assembly for a file
runtime/core/portable_type/tensor_impl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executorch_core.dir/build.make CMakeFiles/executorch_core.dir/runtime/core/portable_type/tensor_impl.cpp.s
.PHONY : runtime/core/portable_type/tensor_impl.cpp.s

runtime/core/tag.o: runtime/core/tag.cpp.o
.PHONY : runtime/core/tag.o

# target to build an object file
runtime/core/tag.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executorch_core.dir/build.make CMakeFiles/executorch_core.dir/runtime/core/tag.cpp.o
.PHONY : runtime/core/tag.cpp.o

runtime/core/tag.i: runtime/core/tag.cpp.i
.PHONY : runtime/core/tag.i

# target to preprocess a source file
runtime/core/tag.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executorch_core.dir/build.make CMakeFiles/executorch_core.dir/runtime/core/tag.cpp.i
.PHONY : runtime/core/tag.cpp.i

runtime/core/tag.s: runtime/core/tag.cpp.s
.PHONY : runtime/core/tag.s

# target to generate assembly for a file
runtime/core/tag.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executorch_core.dir/build.make CMakeFiles/executorch_core.dir/runtime/core/tag.cpp.s
.PHONY : runtime/core/tag.cpp.s

runtime/core/tensor_layout.o: runtime/core/tensor_layout.cpp.o
.PHONY : runtime/core/tensor_layout.o

# target to build an object file
runtime/core/tensor_layout.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executorch_core.dir/build.make CMakeFiles/executorch_core.dir/runtime/core/tensor_layout.cpp.o
.PHONY : runtime/core/tensor_layout.cpp.o

runtime/core/tensor_layout.i: runtime/core/tensor_layout.cpp.i
.PHONY : runtime/core/tensor_layout.i

# target to preprocess a source file
runtime/core/tensor_layout.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executorch_core.dir/build.make CMakeFiles/executorch_core.dir/runtime/core/tensor_layout.cpp.i
.PHONY : runtime/core/tensor_layout.cpp.i

runtime/core/tensor_layout.s: runtime/core/tensor_layout.cpp.s
.PHONY : runtime/core/tensor_layout.s

# target to generate assembly for a file
runtime/core/tensor_layout.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executorch_core.dir/build.make CMakeFiles/executorch_core.dir/runtime/core/tensor_layout.cpp.s
.PHONY : runtime/core/tensor_layout.cpp.s

runtime/executor/method.o: runtime/executor/method.cpp.o
.PHONY : runtime/executor/method.o

# target to build an object file
runtime/executor/method.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executorch_core.dir/build.make CMakeFiles/executorch_core.dir/runtime/executor/method.cpp.o
.PHONY : runtime/executor/method.cpp.o

runtime/executor/method.i: runtime/executor/method.cpp.i
.PHONY : runtime/executor/method.i

# target to preprocess a source file
runtime/executor/method.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executorch_core.dir/build.make CMakeFiles/executorch_core.dir/runtime/executor/method.cpp.i
.PHONY : runtime/executor/method.cpp.i

runtime/executor/method.s: runtime/executor/method.cpp.s
.PHONY : runtime/executor/method.s

# target to generate assembly for a file
runtime/executor/method.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executorch_core.dir/build.make CMakeFiles/executorch_core.dir/runtime/executor/method.cpp.s
.PHONY : runtime/executor/method.cpp.s

runtime/executor/method_meta.o: runtime/executor/method_meta.cpp.o
.PHONY : runtime/executor/method_meta.o

# target to build an object file
runtime/executor/method_meta.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executorch_core.dir/build.make CMakeFiles/executorch_core.dir/runtime/executor/method_meta.cpp.o
.PHONY : runtime/executor/method_meta.cpp.o

runtime/executor/method_meta.i: runtime/executor/method_meta.cpp.i
.PHONY : runtime/executor/method_meta.i

# target to preprocess a source file
runtime/executor/method_meta.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executorch_core.dir/build.make CMakeFiles/executorch_core.dir/runtime/executor/method_meta.cpp.i
.PHONY : runtime/executor/method_meta.cpp.i

runtime/executor/method_meta.s: runtime/executor/method_meta.cpp.s
.PHONY : runtime/executor/method_meta.s

# target to generate assembly for a file
runtime/executor/method_meta.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executorch_core.dir/build.make CMakeFiles/executorch_core.dir/runtime/executor/method_meta.cpp.s
.PHONY : runtime/executor/method_meta.cpp.s

runtime/executor/program.o: runtime/executor/program.cpp.o
.PHONY : runtime/executor/program.o

# target to build an object file
runtime/executor/program.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executorch_core.dir/build.make CMakeFiles/executorch_core.dir/runtime/executor/program.cpp.o
.PHONY : runtime/executor/program.cpp.o

runtime/executor/program.i: runtime/executor/program.cpp.i
.PHONY : runtime/executor/program.i

# target to preprocess a source file
runtime/executor/program.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executorch_core.dir/build.make CMakeFiles/executorch_core.dir/runtime/executor/program.cpp.i
.PHONY : runtime/executor/program.cpp.i

runtime/executor/program.s: runtime/executor/program.cpp.s
.PHONY : runtime/executor/program.s

# target to generate assembly for a file
runtime/executor/program.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executorch_core.dir/build.make CMakeFiles/executorch_core.dir/runtime/executor/program.cpp.s
.PHONY : runtime/executor/program.cpp.s

runtime/executor/program_validation.o: runtime/executor/program_validation.cpp.o
.PHONY : runtime/executor/program_validation.o

# target to build an object file
runtime/executor/program_validation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executorch_core.dir/build.make CMakeFiles/executorch_core.dir/runtime/executor/program_validation.cpp.o
.PHONY : runtime/executor/program_validation.cpp.o

runtime/executor/program_validation.i: runtime/executor/program_validation.cpp.i
.PHONY : runtime/executor/program_validation.i

# target to preprocess a source file
runtime/executor/program_validation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executorch_core.dir/build.make CMakeFiles/executorch_core.dir/runtime/executor/program_validation.cpp.i
.PHONY : runtime/executor/program_validation.cpp.i

runtime/executor/program_validation.s: runtime/executor/program_validation.cpp.s
.PHONY : runtime/executor/program_validation.s

# target to generate assembly for a file
runtime/executor/program_validation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executorch_core.dir/build.make CMakeFiles/executorch_core.dir/runtime/executor/program_validation.cpp.s
.PHONY : runtime/executor/program_validation.cpp.s

runtime/executor/pte_data_map.o: runtime/executor/pte_data_map.cpp.o
.PHONY : runtime/executor/pte_data_map.o

# target to build an object file
runtime/executor/pte_data_map.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executorch_core.dir/build.make CMakeFiles/executorch_core.dir/runtime/executor/pte_data_map.cpp.o
.PHONY : runtime/executor/pte_data_map.cpp.o

runtime/executor/pte_data_map.i: runtime/executor/pte_data_map.cpp.i
.PHONY : runtime/executor/pte_data_map.i

# target to preprocess a source file
runtime/executor/pte_data_map.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executorch_core.dir/build.make CMakeFiles/executorch_core.dir/runtime/executor/pte_data_map.cpp.i
.PHONY : runtime/executor/pte_data_map.cpp.i

runtime/executor/pte_data_map.s: runtime/executor/pte_data_map.cpp.s
.PHONY : runtime/executor/pte_data_map.s

# target to generate assembly for a file
runtime/executor/pte_data_map.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executorch_core.dir/build.make CMakeFiles/executorch_core.dir/runtime/executor/pte_data_map.cpp.s
.PHONY : runtime/executor/pte_data_map.cpp.s

runtime/executor/tensor_parser_exec_aten.o: runtime/executor/tensor_parser_exec_aten.cpp.o
.PHONY : runtime/executor/tensor_parser_exec_aten.o

# target to build an object file
runtime/executor/tensor_parser_exec_aten.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executorch_core.dir/build.make CMakeFiles/executorch_core.dir/runtime/executor/tensor_parser_exec_aten.cpp.o
.PHONY : runtime/executor/tensor_parser_exec_aten.cpp.o

runtime/executor/tensor_parser_exec_aten.i: runtime/executor/tensor_parser_exec_aten.cpp.i
.PHONY : runtime/executor/tensor_parser_exec_aten.i

# target to preprocess a source file
runtime/executor/tensor_parser_exec_aten.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executorch_core.dir/build.make CMakeFiles/executorch_core.dir/runtime/executor/tensor_parser_exec_aten.cpp.i
.PHONY : runtime/executor/tensor_parser_exec_aten.cpp.i

runtime/executor/tensor_parser_exec_aten.s: runtime/executor/tensor_parser_exec_aten.cpp.s
.PHONY : runtime/executor/tensor_parser_exec_aten.s

# target to generate assembly for a file
runtime/executor/tensor_parser_exec_aten.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executorch_core.dir/build.make CMakeFiles/executorch_core.dir/runtime/executor/tensor_parser_exec_aten.cpp.s
.PHONY : runtime/executor/tensor_parser_exec_aten.cpp.s

runtime/executor/tensor_parser_portable.o: runtime/executor/tensor_parser_portable.cpp.o
.PHONY : runtime/executor/tensor_parser_portable.o

# target to build an object file
runtime/executor/tensor_parser_portable.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executorch_core.dir/build.make CMakeFiles/executorch_core.dir/runtime/executor/tensor_parser_portable.cpp.o
.PHONY : runtime/executor/tensor_parser_portable.cpp.o

runtime/executor/tensor_parser_portable.i: runtime/executor/tensor_parser_portable.cpp.i
.PHONY : runtime/executor/tensor_parser_portable.i

# target to preprocess a source file
runtime/executor/tensor_parser_portable.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executorch_core.dir/build.make CMakeFiles/executorch_core.dir/runtime/executor/tensor_parser_portable.cpp.i
.PHONY : runtime/executor/tensor_parser_portable.cpp.i

runtime/executor/tensor_parser_portable.s: runtime/executor/tensor_parser_portable.cpp.s
.PHONY : runtime/executor/tensor_parser_portable.s

# target to generate assembly for a file
runtime/executor/tensor_parser_portable.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executorch_core.dir/build.make CMakeFiles/executorch_core.dir/runtime/executor/tensor_parser_portable.cpp.s
.PHONY : runtime/executor/tensor_parser_portable.cpp.s

runtime/executor/test/test_backend_compiler_lib.o: runtime/executor/test/test_backend_compiler_lib.cpp.o
.PHONY : runtime/executor/test/test_backend_compiler_lib.o

# target to build an object file
runtime/executor/test/test_backend_compiler_lib.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executor_runner.dir/build.make CMakeFiles/executor_runner.dir/runtime/executor/test/test_backend_compiler_lib.cpp.o
.PHONY : runtime/executor/test/test_backend_compiler_lib.cpp.o

runtime/executor/test/test_backend_compiler_lib.i: runtime/executor/test/test_backend_compiler_lib.cpp.i
.PHONY : runtime/executor/test/test_backend_compiler_lib.i

# target to preprocess a source file
runtime/executor/test/test_backend_compiler_lib.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executor_runner.dir/build.make CMakeFiles/executor_runner.dir/runtime/executor/test/test_backend_compiler_lib.cpp.i
.PHONY : runtime/executor/test/test_backend_compiler_lib.cpp.i

runtime/executor/test/test_backend_compiler_lib.s: runtime/executor/test/test_backend_compiler_lib.cpp.s
.PHONY : runtime/executor/test/test_backend_compiler_lib.s

# target to generate assembly for a file
runtime/executor/test/test_backend_compiler_lib.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executor_runner.dir/build.make CMakeFiles/executor_runner.dir/runtime/executor/test/test_backend_compiler_lib.cpp.s
.PHONY : runtime/executor/test/test_backend_compiler_lib.cpp.s

runtime/kernel/operator_registry.o: runtime/kernel/operator_registry.cpp.o
.PHONY : runtime/kernel/operator_registry.o

# target to build an object file
runtime/kernel/operator_registry.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executorch_core.dir/build.make CMakeFiles/executorch_core.dir/runtime/kernel/operator_registry.cpp.o
.PHONY : runtime/kernel/operator_registry.cpp.o

runtime/kernel/operator_registry.i: runtime/kernel/operator_registry.cpp.i
.PHONY : runtime/kernel/operator_registry.i

# target to preprocess a source file
runtime/kernel/operator_registry.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executorch_core.dir/build.make CMakeFiles/executorch_core.dir/runtime/kernel/operator_registry.cpp.i
.PHONY : runtime/kernel/operator_registry.cpp.i

runtime/kernel/operator_registry.s: runtime/kernel/operator_registry.cpp.s
.PHONY : runtime/kernel/operator_registry.s

# target to generate assembly for a file
runtime/kernel/operator_registry.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executorch_core.dir/build.make CMakeFiles/executorch_core.dir/runtime/kernel/operator_registry.cpp.s
.PHONY : runtime/kernel/operator_registry.cpp.s

runtime/platform/abort.o: runtime/platform/abort.cpp.o
.PHONY : runtime/platform/abort.o

# target to build an object file
runtime/platform/abort.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executorch_core.dir/build.make CMakeFiles/executorch_core.dir/runtime/platform/abort.cpp.o
.PHONY : runtime/platform/abort.cpp.o

runtime/platform/abort.i: runtime/platform/abort.cpp.i
.PHONY : runtime/platform/abort.i

# target to preprocess a source file
runtime/platform/abort.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executorch_core.dir/build.make CMakeFiles/executorch_core.dir/runtime/platform/abort.cpp.i
.PHONY : runtime/platform/abort.cpp.i

runtime/platform/abort.s: runtime/platform/abort.cpp.s
.PHONY : runtime/platform/abort.s

# target to generate assembly for a file
runtime/platform/abort.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executorch_core.dir/build.make CMakeFiles/executorch_core.dir/runtime/platform/abort.cpp.s
.PHONY : runtime/platform/abort.cpp.s

runtime/platform/default/posix.o: runtime/platform/default/posix.cpp.o
.PHONY : runtime/platform/default/posix.o

# target to build an object file
runtime/platform/default/posix.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executorch_core.dir/build.make CMakeFiles/executorch_core.dir/runtime/platform/default/posix.cpp.o
.PHONY : runtime/platform/default/posix.cpp.o

runtime/platform/default/posix.i: runtime/platform/default/posix.cpp.i
.PHONY : runtime/platform/default/posix.i

# target to preprocess a source file
runtime/platform/default/posix.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executorch_core.dir/build.make CMakeFiles/executorch_core.dir/runtime/platform/default/posix.cpp.i
.PHONY : runtime/platform/default/posix.cpp.i

runtime/platform/default/posix.s: runtime/platform/default/posix.cpp.s
.PHONY : runtime/platform/default/posix.s

# target to generate assembly for a file
runtime/platform/default/posix.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executorch_core.dir/build.make CMakeFiles/executorch_core.dir/runtime/platform/default/posix.cpp.s
.PHONY : runtime/platform/default/posix.cpp.s

runtime/platform/log.o: runtime/platform/log.cpp.o
.PHONY : runtime/platform/log.o

# target to build an object file
runtime/platform/log.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executorch_core.dir/build.make CMakeFiles/executorch_core.dir/runtime/platform/log.cpp.o
.PHONY : runtime/platform/log.cpp.o

runtime/platform/log.i: runtime/platform/log.cpp.i
.PHONY : runtime/platform/log.i

# target to preprocess a source file
runtime/platform/log.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executorch_core.dir/build.make CMakeFiles/executorch_core.dir/runtime/platform/log.cpp.i
.PHONY : runtime/platform/log.cpp.i

runtime/platform/log.s: runtime/platform/log.cpp.s
.PHONY : runtime/platform/log.s

# target to generate assembly for a file
runtime/platform/log.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executorch_core.dir/build.make CMakeFiles/executorch_core.dir/runtime/platform/log.cpp.s
.PHONY : runtime/platform/log.cpp.s

runtime/platform/platform.o: runtime/platform/platform.cpp.o
.PHONY : runtime/platform/platform.o

# target to build an object file
runtime/platform/platform.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executorch_core.dir/build.make CMakeFiles/executorch_core.dir/runtime/platform/platform.cpp.o
.PHONY : runtime/platform/platform.cpp.o

runtime/platform/platform.i: runtime/platform/platform.cpp.i
.PHONY : runtime/platform/platform.i

# target to preprocess a source file
runtime/platform/platform.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executorch_core.dir/build.make CMakeFiles/executorch_core.dir/runtime/platform/platform.cpp.i
.PHONY : runtime/platform/platform.cpp.i

runtime/platform/platform.s: runtime/platform/platform.cpp.s
.PHONY : runtime/platform/platform.s

# target to generate assembly for a file
runtime/platform/platform.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executorch_core.dir/build.make CMakeFiles/executorch_core.dir/runtime/platform/platform.cpp.s
.PHONY : runtime/platform/platform.cpp.s

runtime/platform/profiler.o: runtime/platform/profiler.cpp.o
.PHONY : runtime/platform/profiler.o

# target to build an object file
runtime/platform/profiler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executorch_core.dir/build.make CMakeFiles/executorch_core.dir/runtime/platform/profiler.cpp.o
.PHONY : runtime/platform/profiler.cpp.o

runtime/platform/profiler.i: runtime/platform/profiler.cpp.i
.PHONY : runtime/platform/profiler.i

# target to preprocess a source file
runtime/platform/profiler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executorch_core.dir/build.make CMakeFiles/executorch_core.dir/runtime/platform/profiler.cpp.i
.PHONY : runtime/platform/profiler.cpp.i

runtime/platform/profiler.s: runtime/platform/profiler.cpp.s
.PHONY : runtime/platform/profiler.s

# target to generate assembly for a file
runtime/platform/profiler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executorch_core.dir/build.make CMakeFiles/executorch_core.dir/runtime/platform/profiler.cpp.s
.PHONY : runtime/platform/profiler.cpp.s

runtime/platform/runtime.o: runtime/platform/runtime.cpp.o
.PHONY : runtime/platform/runtime.o

# target to build an object file
runtime/platform/runtime.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executorch_core.dir/build.make CMakeFiles/executorch_core.dir/runtime/platform/runtime.cpp.o
.PHONY : runtime/platform/runtime.cpp.o

runtime/platform/runtime.i: runtime/platform/runtime.cpp.i
.PHONY : runtime/platform/runtime.i

# target to preprocess a source file
runtime/platform/runtime.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executorch_core.dir/build.make CMakeFiles/executorch_core.dir/runtime/platform/runtime.cpp.i
.PHONY : runtime/platform/runtime.cpp.i

runtime/platform/runtime.s: runtime/platform/runtime.cpp.s
.PHONY : runtime/platform/runtime.s

# target to generate assembly for a file
runtime/platform/runtime.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executorch_core.dir/build.make CMakeFiles/executorch_core.dir/runtime/platform/runtime.cpp.s
.PHONY : runtime/platform/runtime.cpp.s

schema/extended_header.o: schema/extended_header.cpp.o
.PHONY : schema/extended_header.o

# target to build an object file
schema/extended_header.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executorch_core.dir/build.make CMakeFiles/executorch_core.dir/schema/extended_header.cpp.o
.PHONY : schema/extended_header.cpp.o

schema/extended_header.i: schema/extended_header.cpp.i
.PHONY : schema/extended_header.i

# target to preprocess a source file
schema/extended_header.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executorch_core.dir/build.make CMakeFiles/executorch_core.dir/schema/extended_header.cpp.i
.PHONY : schema/extended_header.cpp.i

schema/extended_header.s: schema/extended_header.cpp.s
.PHONY : schema/extended_header.s

# target to generate assembly for a file
schema/extended_header.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executorch_core.dir/build.make CMakeFiles/executorch_core.dir/schema/extended_header.cpp.s
.PHONY : schema/extended_header.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... flatbuffers_ep"
	@echo "... flatcc_ep"
	@echo "... XNNPACK"
	@echo "... common_schema"
	@echo "... cpuinfo"
	@echo "... cpuinfo_internals"
	@echo "... executor_runner"
	@echo "... executorch"
	@echo "... executorch_core"
	@echo "... extension_data_loader"
	@echo "... extension_evalue_util"
	@echo "... extension_flat_tensor"
	@echo "... extension_runner_util"
	@echo "... extension_tensor"
	@echo "... extension_threadpool"
	@echo "... flat_tensor_schema"
	@echo "... flatccrt"
	@echo "... gflags_nothreads_static"
	@echo "... kernels_util_all_deps"
	@echo "... kleidiai"
	@echo "... portable_kernels"
	@echo "... portable_ops_lib"
	@echo "... program_schema"
	@echo "... pthreadpool"
	@echo "... qnn_backend"
	@echo "... qnn_backend_cache"
	@echo "... qnn_backend_options"
	@echo "... qnn_backend_unified_registry"
	@echo "... qnn_context"
	@echo "... qnn_custom_protocol"
	@echo "... qnn_device"
	@echo "... qnn_dlc_manager"
	@echo "... qnn_executorch_backend"
	@echo "... qnn_executorch_logging"
	@echo "... qnn_factory"
	@echo "... qnn_graph"
	@echo "... qnn_implementation"
	@echo "... qnn_logger"
	@echo "... qnn_manager"
	@echo "... qnn_mem_manager"
	@echo "... qnn_op_package_manager"
	@echo "... qnn_profiler"
	@echo "... qnn_schema"
	@echo "... qnn_sys_implementation"
	@echo "... scalar_type_schema"
	@echo "... shared_buffer"
	@echo "... wrappers"
	@echo "... xnnpack-allocator"
	@echo "... xnnpack-cache"
	@echo "... xnnpack-datatype"
	@echo "... xnnpack-fingerprint-cache"
	@echo "... xnnpack-fingerprint-check"
	@echo "... xnnpack-fingerprint-id"
	@echo "... xnnpack-hardware-config"
	@echo "... xnnpack-indirection"
	@echo "... xnnpack-logging"
	@echo "... xnnpack-memory"
	@echo "... xnnpack-microkernel-utils"
	@echo "... xnnpack-microkernels-prod"
	@echo "... xnnpack-microparams-init"
	@echo "... xnnpack-mutex"
	@echo "... xnnpack-normalization"
	@echo "... xnnpack-operator-delete"
	@echo "... xnnpack-operator-run"
	@echo "... xnnpack-operator-utils"
	@echo "... xnnpack-operators"
	@echo "... xnnpack-pack-lh"
	@echo "... xnnpack-packing"
	@echo "... xnnpack-reference-ukernels"
	@echo "... xnnpack-sanitizers"
	@echo "... xnnpack-subgraph"
	@echo "... xnnpack_backend"
	@echo "... xnnpack_schema"
	@echo "... examples/portable/executor_runner/executor_runner.o"
	@echo "... examples/portable/executor_runner/executor_runner.i"
	@echo "... examples/portable/executor_runner/executor_runner.s"
	@echo "... extension/data_loader/file_data_loader.o"
	@echo "... extension/data_loader/file_data_loader.i"
	@echo "... extension/data_loader/file_data_loader.s"
	@echo "... kernels/prim_ops/et_copy_index.o"
	@echo "... kernels/prim_ops/et_copy_index.i"
	@echo "... kernels/prim_ops/et_copy_index.s"
	@echo "... kernels/prim_ops/et_view.o"
	@echo "... kernels/prim_ops/et_view.i"
	@echo "... kernels/prim_ops/et_view.s"
	@echo "... kernels/prim_ops/register_prim_ops.o"
	@echo "... kernels/prim_ops/register_prim_ops.i"
	@echo "... kernels/prim_ops/register_prim_ops.s"
	@echo "... runtime/backend/interface.o"
	@echo "... runtime/backend/interface.i"
	@echo "... runtime/backend/interface.s"
	@echo "... runtime/core/evalue.o"
	@echo "... runtime/core/evalue.i"
	@echo "... runtime/core/evalue.s"
	@echo "... runtime/core/exec_aten/util/tensor_shape_to_c_string.o"
	@echo "... runtime/core/exec_aten/util/tensor_shape_to_c_string.i"
	@echo "... runtime/core/exec_aten/util/tensor_shape_to_c_string.s"
	@echo "... runtime/core/exec_aten/util/tensor_util_portable.o"
	@echo "... runtime/core/exec_aten/util/tensor_util_portable.i"
	@echo "... runtime/core/exec_aten/util/tensor_util_portable.s"
	@echo "... runtime/core/portable_type/tensor_impl.o"
	@echo "... runtime/core/portable_type/tensor_impl.i"
	@echo "... runtime/core/portable_type/tensor_impl.s"
	@echo "... runtime/core/tag.o"
	@echo "... runtime/core/tag.i"
	@echo "... runtime/core/tag.s"
	@echo "... runtime/core/tensor_layout.o"
	@echo "... runtime/core/tensor_layout.i"
	@echo "... runtime/core/tensor_layout.s"
	@echo "... runtime/executor/method.o"
	@echo "... runtime/executor/method.i"
	@echo "... runtime/executor/method.s"
	@echo "... runtime/executor/method_meta.o"
	@echo "... runtime/executor/method_meta.i"
	@echo "... runtime/executor/method_meta.s"
	@echo "... runtime/executor/program.o"
	@echo "... runtime/executor/program.i"
	@echo "... runtime/executor/program.s"
	@echo "... runtime/executor/program_validation.o"
	@echo "... runtime/executor/program_validation.i"
	@echo "... runtime/executor/program_validation.s"
	@echo "... runtime/executor/pte_data_map.o"
	@echo "... runtime/executor/pte_data_map.i"
	@echo "... runtime/executor/pte_data_map.s"
	@echo "... runtime/executor/tensor_parser_exec_aten.o"
	@echo "... runtime/executor/tensor_parser_exec_aten.i"
	@echo "... runtime/executor/tensor_parser_exec_aten.s"
	@echo "... runtime/executor/tensor_parser_portable.o"
	@echo "... runtime/executor/tensor_parser_portable.i"
	@echo "... runtime/executor/tensor_parser_portable.s"
	@echo "... runtime/executor/test/test_backend_compiler_lib.o"
	@echo "... runtime/executor/test/test_backend_compiler_lib.i"
	@echo "... runtime/executor/test/test_backend_compiler_lib.s"
	@echo "... runtime/kernel/operator_registry.o"
	@echo "... runtime/kernel/operator_registry.i"
	@echo "... runtime/kernel/operator_registry.s"
	@echo "... runtime/platform/abort.o"
	@echo "... runtime/platform/abort.i"
	@echo "... runtime/platform/abort.s"
	@echo "... runtime/platform/default/posix.o"
	@echo "... runtime/platform/default/posix.i"
	@echo "... runtime/platform/default/posix.s"
	@echo "... runtime/platform/log.o"
	@echo "... runtime/platform/log.i"
	@echo "... runtime/platform/log.s"
	@echo "... runtime/platform/platform.o"
	@echo "... runtime/platform/platform.i"
	@echo "... runtime/platform/platform.s"
	@echo "... runtime/platform/profiler.o"
	@echo "... runtime/platform/profiler.i"
	@echo "... runtime/platform/profiler.s"
	@echo "... runtime/platform/runtime.o"
	@echo "... runtime/platform/runtime.i"
	@echo "... runtime/platform/runtime.s"
	@echo "... schema/extended_header.o"
	@echo "... schema/extended_header.i"
	@echo "... schema/extended_header.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

